//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Alert')
export class AlertEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  user: string;

  @Column('text', { nullable: true })
  gameRound: string;

  @Column('text', { nullable: true })
  alertType: string;

  @Column('date', { nullable: true })
  timestamp: Date;
}
