//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Analysis')
export class AnalysisEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Name: string;

  @Column('text', { nullable: true })
  Type: string;

  @Column('text', { nullable: true })
  DataSource: string;

  @Column('text', { nullable: true })
  ChartGraphType: string;

  @Column('date', { nullable: true })
  Timestamp: Date;
}
