//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('DataSource')
export class DataSourceEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Name: string;

  @Column('text', { nullable: true })
  Type: string;

  @Column('real', { nullable: true })
  Duration: number;

  @Column('date', { nullable: true })
  Timestamp: Date;
}
