//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import {
  DataSourceList,
  DataSourceCreate,
  DataSourceEdit,
} from './resources/DataSource';
import {
  PredictionModelList,
  PredictionModelCreate,
  PredictionModelEdit,
} from './resources/PredictionModel';
import { AlertList, AlertCreate, AlertEdit } from './resources/Alert';
import {
  AnalysisList,
  AnalysisCreate,
  AnalysisEdit,
} from './resources/Analysis';
import {
  RealtimeDataList,
  RealtimeDataCreate,
  RealtimeDataEdit,
} from './resources/RealtimeData';
import DataSourceIcon from '@mui/icons-material/Source';
import PredictionModelIcon from '@mui/icons-material/Insights';
import AlertIcon from '@mui/icons-material/NotificationImportant';
import AnalysisIcon from '@mui/icons-material/Analytics';
import RealtimeDataIcon from '@mui/icons-material/Update';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/a6e0a9fd5">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="DataSource"
          options={{ label: 'Data Source' }}
          list={DataSourceList}
          create={DataSourceCreate}
          edit={DataSourceEdit}
          recordRepresentation="Name"
          icon={DataSourceIcon}
        />
        <Resource
          name="PredictionModel"
          options={{ label: 'Prediction Model' }}
          list={PredictionModelList}
          create={PredictionModelCreate}
          edit={PredictionModelEdit}
          recordRepresentation="Name"
          icon={PredictionModelIcon}
        />
        <Resource
          name="Alert"
          options={{ label: 'Alert' }}
          list={AlertList}
          create={AlertCreate}
          edit={AlertEdit}
          recordRepresentation="id"
          icon={AlertIcon}
        />
        <Resource
          name="Analysis"
          options={{ label: 'Analysis' }}
          list={AnalysisList}
          create={AnalysisCreate}
          edit={AnalysisEdit}
          recordRepresentation="Name"
          icon={AnalysisIcon}
        />
        <Resource
          name="RealtimeData"
          options={{ label: 'Real Time Data' }}
          list={RealtimeDataList}
          create={RealtimeDataCreate}
          edit={RealtimeDataEdit}
          recordRepresentation="id"
          icon={RealtimeDataIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
