//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="Avi Predictor" />
    <CardContent>
      I am interested in creating an app that analyses the behaviour of the
      "Aviator" algorithm (referring to the Aviator game, a popular casino-style
      game where the goal is to predict the right time to cash out before the
      plane "flies away")
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
